### ISSUE TITLE
Registry sometimes has incorrect data

### ISSUE THREAD

**Issue by MatthewMartinBBC** [rhastie/build-nmos-cpp#31]
We are attempting to use the NMOS registry with a number of Direct Out Prodigy devices. I've noticed that sometimes after making a PATCH to a receiver on a Prodigy RAV.IO card that the Registry has incorrect data for the receiver.
It has the wrong "label" and "description" and also the wrong "subscription"

I've attached two files. 
registry.json shows the result of querying the registry for the given receiver (x-nmos/query/v1.3/receivers/78c5fc04-2e4f-57c1-8ba6-ea56d91b81cb)
receiver.json shows the result of querying the node itself for the given receiver (x-nmos/node/v1.2/receivers/78c5fc04-2e4f-57c1-8ba6-ea56d91b81cb)

You can see that the labels and descriptions are different after the "[20154c|1]" part of the string. In this case the subscription is the same on both, but I first noticed the bug when doing an immediate activation PATCH to a receiver, getting a 200 response code and then a websocket message from the registry with the false label information and also false subscription information.
[receiver.json](https://github.com/rhastie/build-nmos-cpp/files/14790878/receiver.json)
[registry.json](https://github.com/rhastie/build-nmos-cpp/files/14790879/registry.json)

**Comment by rhastie** [comment]
Matthew,

Are you applying the PATCH to the Registry directly or to the Prodigy RAV.IO NMOS Node?

I'll let others jump in here but if its the later my understanding is this is the responsibility of the receiver (ie. the NMOS Node) itself to update the registry once it's been patched. The registry shouldn't and doesn't maintain WebSocket connections to all of the downstream Nodes and as such it won't know if something changes. It's completely reliant on the NMOS Node to act correctly and update the registry if and when something changes with the actual Node configuration.

I think potentially the issue here is with the NMOS Node implementation. Potentially a good way to prove this theory out is to see if you can replicate the problem using the NMOS Virtual-Node implementation available in the container. This NMOS Node implementation should update the registry if it's PATCH'd.

**Comment by MatthewMartinBBC** [comment]
Hi,
I'm applying the PATCH to a RAV.IO NMOS receiver 
The receiver is running nmos-cpp
The receiver updates the registry - most of the time the registry is then correct
Sometimes however the registry has incorrect information as per the files I attached.

My application subscribes to two registry websocket endpoints, one for Senders and one for Receivers. When my application makes a PATCH to a Receiver it gets a 200 response and the correct JSON back, then the Registry sends my application a websocket message to say the Receiver version has changed and this has the incorrect information.

It is odd that the label and description are correct up to the "]" and then they have the label and description of a Receiver from a completely separate device

Also - once the Registry has the incorrect information this persists on querying it for the receiver JSON

**Comment by rhastie** [comment]
This looks to me like the NMOS implementation hasn't quite got all of it's callbacks correctly setup in the Ravenna receiver. The receiver must update the registry and that doesn't appear be happening here. The registry is wholly reliant on what it's given by the node.

As this implementation is built on nmos-cpp can you try and validate the problem with the virtual-node please? This would narrow the error vector down and pin it to either the nmos-cpp codebase or the Ravenna implementation of nmos-cpp.

**Comment by martim01** [comment]
But that doesn't explain why the registry has incorrect information.

I can see the registry being updated by the rav.io card and the registry updates my application via the web socket.


But the registry is sending and storing information associated with a completely unconnected receiver on a different Prodigy unit.

**Comment by garethsb** [comment]
The Registry is pretty simple, it simply stores the information that devices send it, keyed from the `id` fields, and forwards the information via the Query WebSocket API to clients.

Since you mention that you have multiple RAV.IO devices in your network, would you please check the `id` values of these are all unique and immutable? And perhaps repeat the experiment with only one of the RAV.IO devices powered on?

**Comment by rhastie** [comment]
You also do appear to be using 2 different versions of the NMOS APIs (v1.2 and v1.3) here. This may be as simple as non-matching data between the versions. 

Can you give me the output for "x-nmos/query/**v1.2**/receivers/78c5fc04-2e4f-57c1-8ba6-ea56d91b81cb" on the registry please?

**Comment by martim01** [comment]
Sorry, that was a typo both versions are 1.3

I've checked the registry v1.2 and v1.1 and it has exactly the same incorrect information for the receiver.

**Comment by garethsb** [comment]
Please do check the `id` of all the receivers. Most likely explanation for unexpected data in the Registry is that it was sent unexpected data. You could try configuring the Registry to have more verbose logging (`"logging_level": -40`) and also getting it to write the access log to file (`"access_log": "access-log.txt"`)

**Comment by martim01** [comment]
I'm pretty certain all the IDs are different. Certainly the id of the receiver I send the PATCH to and the id of the one the registry takes the label from are different.

I'll set the log level as suggested and see if there's anything obvious when I do the PATCH.

Thanks

**Comment by garethsb** [comment]
I think we're all pretty perplexed. The Registry doesn't have any code that merges the resource data from multiple resources. It would be even more surprising if one device started sending some values relating to an entirely different device... if the access log and verbose error log don't explain what's going on,  I think you may have to simplify the number of devices involved and/or wireshark the exchanges next.

**Comment by MatthewMartinBBC** [comment]
I ended up running tcpdump on the machine running the registry and it looks as if it's the RAV.IO cards sending the registry incorrect data. I've opened a bug report with them and will close this issue.
Thanks for your help.
